name: Test Action 
# Controls when the action will run.
on:
 # triggers the workflow on push or pull request events but only for the main branch
 
 push:
 
   branches: [main]
   # Allows you to run this workflow manually from the actions tab 
   # Workflow
   # A workflow contains a single job callled "build"
   
   
jobs:
 # This workflow contains a single job called "build"
 
 build: 
 
 # the type of runner that the job will run on.
 
   runs-on: ubuntu-latest
   
   # steps represent a sequence of tasks that will be executed as part of the job
   steps:
    # checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with: 
        node-version: 12
        
    - name: check commands
      run: pwd
      
    - name: Check ls
      run: ls
      
  # Runs a set of commands using the runners shell   
    - name: Install Surge 
      run: npm install surge
      
    - name: Deploy website on surge 
      run: surge ./ https://fuzzy-yarn.surge.sh/ --token ${{ secrets.TEST_SURGE_TOKEN}}
        
   
 
